[package]
name = "gmanim-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "gmanim_core"

[dependencies]
nalgebra = "0.35"
usvg = "0.47"
fern = "*"
log = "*"
humantime = "*"
cfg-if = "1.0.0"
ffmpeg-next = "9.0"
yuv = { version = "0.8.11", features = ["fast_mode"] }
bytemuck = { version = "1.25.0", features = ["derive"] }
ash = "0.38.0"
gpu-allocator = { version = "0.28.0", features = ["vulkan"] }
naga = { version = "29.0.3", features = ["wgsl-in", "spv-out"] }
lyon = "1.0.19"
memoffset = "0.9.1"
slotmap = "1.0.7"

[features]
default = ["gmfloat_f32"]
gmfloat_f32 = []
gmfloat_f64 = []
gmfloat_f16 = []
