[package]
name = "gmanim-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "gmanim_core"

[dependencies]
nalgebra = "0.35"
rusttype = "0.9.3"
usvg = "0.47"
tiny-skia = "0.12"
fern = "*"
log = "*"
humantime = "*"
cfg-if = "1.0.0"
ffmpeg-next = "8.1"
yuv = { version = "0.8.11", features = ["fast_mode"] }

[features]
default = ["gmfloat_f32"]
gmfloat_f32 = []
gmfloat_f64 = []
gmfloat_f16 = []
